### ISSUE TITLE
When a referral is not approved through typeform it still takes up a slot

### ISSUE THREAD

**Issue by ValaCast** [TechforgoodCAST/chc-referrals#12]
It's okay if these need to come into the system but they need to not take up slots until someone on the CHC looks at them and declines them again. Happy to have a chat about it if the issue is confusing.

**Comment by suninthesky** [comment]
Is this when a response from Typeform [automatically declined](https://github.com/TechforgoodCAST/chc-referrals/blob/master/app/models/referral.rb#L66)? I'll take a look. Can you share an example referral that shouldn't have taken up a slot, e.g. `../british-red-cross/referrals/12`?

**Comment by suninthesky** [comment]
_Reminder:_ Typeforms that want to have automatic declining as a feature should use the quiz functionality of Typeform to return a negative score when the form is submitted. E.g. you could ensure this by giving a score of -9999 when an undesirable answer is given.
